Responsive Desktop Version
sabetech/myportfolio-web pull request #5
Opened 2022-02-24 19:43 UTC by sabetech

In this pull request:
- Top navigation menu shows based on device-width
- Main background image switches dependent on the device-width
- Used media queries to detect device and modify page accordingly

2022-02-24 20:44 UTC, Amrhub requested changes
Hi @sabetech,  👋🏻 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!
These changes aim to add some awesomeness to your awesome project and code skills.

## To Highlight ✔️ 
Highly organized and clean code ✔️ 👨🏻‍💻 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 


## Required Changes ♻️
_Check the comments under the review._
![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-24 20:44 UTC, Amrhub commented on style.css
> +  margin: 0 24px 200px 24px;
- [ ] Let's make sure we get rid of unwanted space at the bottom after footer content (in desktop view) to match the Figma design

Your implementation | Figma Design
:------:|:-----:
![image](https://user-images.githubusercontent.com/87689547/155603728-d2f473fe-ab8b-4447-a386-bc22a2aa6ca9.png) | ![image](https://user-images.githubusercontent.com/87689547/155603916-98be9420-972e-41ac-8f57-b887625687a6.png)

2022-02-24 20:44 UTC, Amrhub commented on style.css
> +}
- [ ] Let's make sure in desktop view we don't have these spaces between content to match the Figma design

Your implementation | Figma Design
:------:|:-----:
![image](https://user-images.githubusercontent.com/87689547/155604286-5f738baf-bb8c-4687-a4e4-64a35a10410b.png) | ![image](https://user-images.githubusercontent.com/87689547/155604332-81fdbe5b-4284-4ef2-bf1e-6f731f0e486e.png)

2022-02-25 10:33 UTC, ShoiraTa commented
### **STATUS: APPROVED  ✔️** 
------
Hi @sabetech,  

Your project is complete! There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 
![giphy](https://user-images.githubusercontent.com/77038610/154916093-53a75ff8-ba21-44ad-a25e-bdea6200d8f1.gif)

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-25 11:41 UTC, merged